"""Markdown scorecard from civic audit (heuristic — for human review)."""

from __future__ import annotations

from analysis.civic_audit.analyzer import CivicAuditAnalyzer, CivicAuditResult


def generate_civic_scorecard_markdown(result: CivicAuditResult) -> str:
    n_rules = len(CivicAuditAnalyzer.PATTERN_RULES)
    lines = [
        "# Civic accountability scorecard (heuristic)",
        "",
        f"**Repository:** `{result.repo_path}`",
        f"**Overall score (rough composite):** {result.overall_civic_score:.2f} (not a certification)",
        "",
        "These numbers are coarse heuristics from keywords, AST slices, and file scans.",
        "",
        "## Breakdown",
        "",
        f"- Corruption/pattern coverage (rule name matches): **{result.corruption_detection_score:.2f}**",
        f"  - Distinct named rules seen: **{len(set(result.pattern_rules_found))}** / {n_rules}",
        f"- Temporal indicators (keyword density): **{result.temporal_integrity_score:.2f}**",
        f"  - Files flagged: **{len(result.temporal_logic)}**",
        f"- Crypto/signing-related files (keyword): **{result.cryptographic_robustness_score:.2f}**",
        f"  - Signing flow buckets: **{len(result.signing_flows)}**",
        f"- Transparency/reliability penalty heuristic: **{result.transparency_score:.2f}**",
        "",
        "## Findings",
        "",
    ]

    crit = [f for f in result.findings if f.severity == "critical"]
    if crit:
        lines.append("### Critical / high attention")
        for f in crit[:20]:
            lines.append(f"- **{f.title}** (`{f.file_path}`:{f.line_number}) — {f.description[:200]}")
        lines.append("")
    else:
        lines.append("No **critical**-severity items in this pass (does not prove absence of issues).")
        lines.append("")

    recs = list({f.recommendation for f in result.findings if f.recommendation})[:10]
    if recs:
        lines.append("## Sample recommendations")
        for i, r in enumerate(recs, 1):
            lines.append(f"{i}. {r}")
        lines.append("")

    lines.append("— Generated by Code View civic audit (heuristic).")
    return "\n".join(lines)
